# Generated by Django 2.2.6 on 2019-11-26 08:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='postal_cade',
            new_name='postal_code',
        ),
    ]
